name: MUSIMUESTRAS 2017
markdown: kramdown
highlighter: rouge
exclude: [main.scss, config.rb]
description: Sitio informativo del Programa Museo, Arte y Ciudad - Musimuestras 2017
url: http://fernanz.github.io/
permalink: pretty

collections:
  projects:
    output: true
  people:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: people
    values:
      layout: person
