name: MUSIMUESTRAS 2017
markdown: kramdown
highlighter: rouge
exclude: [main.scss, config.rb]
description: Sitio informativo del Programa Museo, Arte y Ciudad - Musimuestras 2017
url: http://fernanz.github.io/
permalink: pretty

exclude: ['map-faal.html']

collections:
  arts:
    output: true
  people:
    output: true
  capsulas:
    output: true

defaults:
  - scope:
      type: arts
    values:
      layout: ars
  - scope:
      type: people
    values:
      layout: person
  - scope:
      type: capsulas
    values:
      layout: capsule
