name: MUSEO ARTE Y CIUDAD
# kramdown:
#  syntax_highlighter: rouge
#  input: GFM
#  auto_ids:       true
#  toc_levels:     1..3
exclude: [main.scss, config.rb, crono-faal.html, bicentenario.html, guayaquil-ebook.html]
description: Sitio informativo del Programa Museo, Arte y Ciudad - Musimuestras 2017
url: https://museoarteyciudad.com
permalink: pretty

collections:
  arts:
    output: true
  people:
    output: true
  capsulas:
    output: true
  destacadas:
    output: true

defaults:
  - scope:
      type: arts
    values:
      layout: ars
  - scope:
      type: people
    values:
      layout: person
  - scope:
      type: capsulas
    values:
      layout: capsule
