# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FERNANDO MAYORGA
email: fmayorga.uno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Caminando al margen del tiempo, buscando una puerta a otra dimensión.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fernanz.github.io" # the base hostname & protocol for your site
twitter_username: fernanz
github_username:  fernanz
facebook_username: fernando

# Build settings
name: FERNANDO MAYORGA
markdown: kramdown
highlighter: rouge

# Settings extra
collections:
    capsulas:
        output: true
defaults:
  - scope:
      type: capsula
    values:
      layout: post
