name: MUSIMUESTRAS 2017
markdown: kramdown
highlighter: rouge
exclude: [main.scss, config.rb, crono-faal.html]
description: Sitio informativo del Programa Museo, Arte y Ciudad - Musimuestras 2017
url: https://fernanz.github.io/
permalink: pretty

collections:
  arts:
    output: true
  people:
    output: true
  capsulas:
    output: true
  destacadas:
    output: true

defaults:
  - scope:
      type: arts
    values:
      layout: ars
  - scope:
      type: people
    values:
      layout: person
  - scope:
      type: capsulas
    values:
      layout: capsule
